### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by danpersa**

### CODE REVIEW

**Comment by danpersa** [comment]
zappr requires a :thumbsup:

**Comment by Adeynack** [comment]
👍

**Comment by Adeynack** [comment]
@danpersa : Is it worth changing the maintainers file for just 4 days? I am not engaging myself in maintaining this repo after the hack-week.

**Comment by danpersa** [comment]
@Adeynack please remove yourself :)

**Comment by Adeynack** [comment]
👍

**Pull request merged**
