### PR TITLE
#58 auto version with travis

### PR DESCRIPTION
**Pull request by Adeynack**
- add the GITHUB_AUTH encrypted env variable

Let's try again, this time with the GITHUB_AUTH encrypted environment variable

### CODE REVIEW

**Comment by Adeynack** [comment]
👎

**Comment by danpersa** [comment]
:thumbsup:

**Comment by Adeynack** [comment]
:

**Comment by Adeynack** [comment]
👍

**Comment by rgritti** [comment]
:+1:

**Pull request merged**
